### ISSUE TITLE
PHP installer asking for Envato purchase code

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [Supernova3339/anonfiles#36]
PHP installer is asking for Envato purchase code
![Screenshot 2024-09-03 224136](https://github.com/user-attachments/assets/4d13ad10-6ccb-4006-933f-cc235fb2a88e)

If I put "none" there, the installation fails
![Screenshot 2024-09-03 224353](https://github.com/user-attachments/assets/ab05d797-0cd9-4b33-92bc-1c94d3673094)

Note that I am using PHP installation, not docker

**Comment by Supernova3339** [comment]
You can find that in API.php file!
